name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup FTP deployment
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: 192.168.2.11
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftps
          local-dir: ./ # Specify the directory to upload (default is the repository root)
          server-dir: /var/www/html/ # Add a trailing slash to indicate it's a directory
